version: "3.9"

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - sentiment_service
      - custom_service

  sentiment_service:
    build: ./sentiment_classifier
    ports:
      - "8001:8001"

  custom_service:
    build: ./custom_classifier
    ports:
      - "8002:8002"
